### ISSUE TITLE
empty file

### ISSUE THREAD

**Issue by coco22990** [staticshreyas/Attendance-Portal#2]
main.html is empty

**Comment by hashy1901** [comment]
@staticshreyas @Sakshi107 @akshit6 
i have been referring to this project to work on a personal one of mine
please could you sort the issue of main.html being empty to help me

**Comment by staticshreyas** [comment]
Hey! main.html is not required. We are just running a flask server for serving a few back-end APIs. You have to run the node server separately for the front end.
