### ISSUE TITLE
can't store attendance in database 

### ISSUE THREAD

**Issue by SudarshanProCoder** [staticshreyas/Attendance-Portal#6]
../public/assets/uploads\9821.jpg Student has not uploaded an image
../public/assets/uploads\9822.jpg Student has not uploaded an image
Traceback (most recent call last):
  File "G:\Sudarshan\Attendance-Portal-main\Py-Scripts\main.py", line 66, in <module>
    ret, frame = video_capture.read()

**Comment by bit-32** [comment]
have to solved it ? 
can you help me too i am getting same issue

**Comment by SudarshanProCoder** [comment]
> have to solved it ? can you help me too i am getting same issue

actually that main python code is wrong
