### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jeckajecka** [staticshreyas/Attendance-Portal#8]
Hi , 
I would like to ask how can i fix 

PS C:\Users\jesse\Documents\GitHub\Attendance-Portal> cd ./Py-Scripts 
>> pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\jesse\Documents\GitHub\Attendance-Portal\Py-Scripts> python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\python311\lib\site-packages (22.3.1)
Collecting pip
  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\python311\\lib\\site-packages\\pip-22.3.1.dist-info\\entry_points.txt'
Consider using the `--user` option or check the permissions.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\jesse\Documents\GitHub\Attendance-Portal\Py-Scripts> 

i was trying to install the requirements.txt but i can't figure out how, i tried to find solution on google but still error occur. 
please how can i fix it?

**Comment by bit-32** [comment]
Just use pip install -r requirements.txt

**Comment by staticshreyas** [comment]
Closed
